---
- name: check to see if awscli installed
  stat:
    path: /usr/local/bin/aws
  register: aws_result

- name: install awscli
  block:
    - name: install unzip
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: create download dir
      file:
        path: /root/awscli
        state: directory
        mode: '0755'

    - name: download awscli
      get_url:
        url: 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip'
        dest: /root/awscli/archive.zip
        mode: '0700'

    - name: unarchive awscli
      unarchive:
        src: /root/awscli/archive.zip
        remote_src: yes
        dest: /root/awscli

    - name: install awscli
      command: /root/awscli/aws/install
  when: not aws_result.stat.exists

- name: copy sync script
  template:
    src: blockchain_sync.sh.j2
    dest: /root/{{ chain }}_blockchain_sync.sh
    owner: root
    group: root
    mode: '0700'

- name: register sync script to cron
  cron:
    name: "Blockchain sync to S3"
    minute: "*/15"
    job: "/root/{{ chain }}_blockchain_sync.sh"