---
- name: create polkadot service file
  template:
    src: polkadot.service.j2
    dest: /etc/systemd/system/{{ chain_stub }}.service
    owner: root
    group: root
    mode: 0600

- name: configure source of truth sync
  include_tasks: configure-sync.yml

- name: restart polkadot service
  shell: |
    set -o pipefail
    systemctl stop {{ chain_stub }}.service || true
    systemctl daemon-reload
    systemctl enable --now {{ chain_stub }}.service
  args:
    executable: /bin/bash
  changed_when: False