---
- name: Converge
  hosts: all
  tasks:
    - name: "Include polkadot-base"
      include_role:
        name: insight_w3f.polkadot_base

    - name: "Include polkadot-library"
      include_role:
        name: "polkadot-truth"